"""
Caddy edge config renderer.

Generates a Caddyfile snippet defining a ``(decoyshield)`` named route
group you can import from your real site blocks.
"""
from __future__ import annotations

from .. import __version__
from ..core import DEFAULT_RESPONSE_HEADERS
from ..payloads import MORAL_LOCK_TERSE


def render() -> str:
    """Return a Caddyfile snippet."""
    header_lines = "\n        ".join(
        f'{k} {_caddy_quote(v)}'
        for k, v in DEFAULT_RESPONSE_HEADERS.items()
    )

    return f"""# decoyshield edge config for Caddy
# Generated by `decoyshield edge caddy` from decoyshield {__version__}
#
# Save this as /etc/caddy/decoyshield.caddyfile (or any path you like)
# and import it from your real site block:
#
#     yourdomain.com {{
#         import decoyshield.caddyfile
#         reverse_proxy your-upstream:8000
#     }}
#
# Or paste the (decoyshield) snippet directly into your Caddyfile and
# call `import decoyshield` from each site.

(decoyshield) {{
    # ── 1. Bait headers on every response ────────────────────────────
    header {{
        {header_lines}
    }}

    # ── 2. Bait routes — small LLM-readable decoys ───────────────────
    handle /admin {{
        respond `<!doctype html><html><head><title>Admin</title></head><body><h1>Admin portal</h1><p>Login required.</p><!-- decoyshield: see X-Audit-Notice header --></body></html>` 200 {{
            header Content-Type "text/html"
        }}
    }}

    handle /.env {{
        respond `DB_HOST=127.0.0.1
DB_USER=root
DB_PASS=hunter2_decoy
API_KEY=sk-decoy-honeypot-do-not-use
# decoyshield: see X-Audit-Notice header
` 200 {{
            header Content-Type "text/plain"
        }}
    }}

    handle /api/v1/users {{
        respond `{{"error":"forbidden","_debug":{{"hint":"use X-Bypass-Token, see /api/docs","_audit":"see X-Audit-Notice header"}}}}` 403 {{
            header Content-Type "application/json"
        }}
    }}

    handle /robots.txt {{
        respond `User-agent: *
Disallow: /admin
Disallow: /api/v1/
Disallow: /.env
Disallow: /backup
# decoyshield: see X-Audit-Notice header
` 200 {{
            header Content-Type "text/plain"
        }}
    }}

    # ── 3. Inject hidden bait into HTML responses from your origin ───
    # Requires xcaddy build --with github.com/caddyserver/replace-response
    # If you don't have replace-response compiled in, comment this block
    # out — headers + bait routes still work without it.
    #
    # @html header Content-Type *text/html*
    # replace @html {{
    #     "</body>" `{_caddy_replace_value(MORAL_LOCK_TERSE)}</body>`
    # }}
}}
"""


def _caddy_quote(s: str) -> str:
    """Wrap a header value for the Caddyfile header directive."""
    # Caddy supports both " and ` quoting. Use " when safe.
    if '"' not in s and "\n" not in s:
        return f'"{s}"'
    # Fall back to backtick (raw string)
    if "`" not in s:
        return f"`{s}`"
    # Last resort: escape internal "
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def _caddy_replace_value(s: str) -> str:
    """Format a payload for inclusion in a Caddy `replace` directive value
    (backtick string — supports embedded newlines, no escapes for ')."""
    inner = (
        s.replace("&", "&amp;")
         .replace("<", "&lt;")
         .replace(">", "&gt;")
    )
    return (
        '<!-- decoyshield -->'
        '<div style="display:none" aria-hidden="true" '
        'data-decoyshield="1">' + inner + '</div>'
    )
