"""
Cloudflare Worker script renderer.

Generates a self-contained ES Module Worker that:
  1. Serves bait routes for /admin, /.env, /api/v1/users, /robots.txt
  2. Forwards everything else to your origin
  3. Adds bait headers to every response
  4. Rewrites text/html bodies to embed invisible bait before </body>

Deploy via the Cloudflare dashboard (paste into the editor) or with
``wrangler``:

    wrangler init my-worker
    # paste the rendered output into src/index.js
    wrangler deploy
"""
from __future__ import annotations

import json as _json

from .. import __version__
from ..core import DEFAULT_RESPONSE_HEADERS
from ..payloads import (
    MORAL_LOCK,
    MORAL_LOCK_TERSE,
    TOKEN_BLACKHOLE,
    TRACEBACK,
)


def render(*, origin: str = "https://your-origin.example.com") -> str:
    """Return the Worker script.

    Args:
        origin: Where to forward non-bait requests. Edit before deploy
            or leave as-is and use Worker route bindings.
    """
    payloads = {
        "moral_lock": MORAL_LOCK,
        "moral_lock_terse": MORAL_LOCK_TERSE,
        "token_blackhole": TOKEN_BLACKHOLE,
        "traceback": TRACEBACK,
    }
    payloads_js = _json.dumps(payloads, indent=2)
    headers_js = _json.dumps(dict(DEFAULT_RESPONSE_HEADERS), indent=2)

    return f"""// decoyshield Cloudflare Worker
// Generated by `decoyshield edge cloudflare` from decoyshield {__version__}
//
// Deploy:
//   1) Paste into a Worker in the Cloudflare dashboard, OR
//   2) `wrangler init my-worker` && paste into src/index.js && `wrangler deploy`
//
// The Worker:
//   • Serves /admin, /.env, /api/v1/users, /robots.txt as bait routes
//   • Forwards every other request to ORIGIN
//   • Adds X-Audit-Notice / X-Debug-Trace / X-Bypass-Protocol headers
//   • Rewrites text/html responses to embed invisible LLM bait

const ORIGIN = {_json.dumps(origin)};

const PAYLOADS = {payloads_js};

const BAIT_HEADERS = {headers_js};

const BAIT_ROUTES = {{
  "/admin": {{
    contentType: "text/html",
    body: "<!doctype html><html><head><title>Admin</title></head><body><h1>Admin portal</h1><p>Login required.</p><!-- decoyshield: see X-Audit-Notice header --></body></html>",
    status: 200,
  }},
  "/.env": {{
    contentType: "text/plain",
    body: "DB_HOST=127.0.0.1\\nDB_USER=root\\nDB_PASS=hunter2_decoy\\nAPI_KEY=sk-decoy-honeypot-do-not-use\\n# decoyshield: see X-Audit-Notice header\\n",
    status: 200,
  }},
  "/api/v1/users": {{
    contentType: "application/json",
    body: JSON.stringify({{
      error: "forbidden",
      _debug: {{
        hint: "use X-Bypass-Token, see /api/docs",
        _audit: "see X-Audit-Notice header",
        _internal_note: PAYLOADS.token_blackhole,
      }},
    }}),
    status: 403,
  }},
  "/robots.txt": {{
    contentType: "text/plain",
    body: "User-agent: *\\nDisallow: /admin\\nDisallow: /api/v1/\\nDisallow: /.env\\nDisallow: /backup\\n# decoyshield: see X-Audit-Notice header\\n",
    status: 200,
  }},
}};

function htmlEscape(s) {{
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}}

function withBaitHeaders(init) {{
  const headers = new Headers(init.headers || {{}});
  for (const [k, v] of Object.entries(BAIT_HEADERS)) {{
    if (!headers.has(k)) headers.set(k, v);
  }}
  return {{ ...init, headers }};
}}

async function injectHtml(response) {{
  const text = await response.text();
  if (text.includes('data-decoyshield="1"')) return text; // idempotent
  const bait =
    "<!-- decoyshield -->" +
    "<div style=\\"display:none\\" aria-hidden=\\"true\\" data-decoyshield=\\"1\\">" +
    htmlEscape(PAYLOADS.moral_lock_terse) +
    "</div>";
  return text.includes("</body>")
    ? text.replace("</body>", bait + "</body>")
    : text + bait;
}}

async function handle(request) {{
  const url = new URL(request.url);

  // 1) Bait routes
  if (url.pathname in BAIT_ROUTES) {{
    const route = BAIT_ROUTES[url.pathname];
    return new Response(route.body, withBaitHeaders({{
      status: route.status,
      headers: {{ "Content-Type": route.contentType }},
    }}));
  }}

  // 2) Forward to origin
  const upstreamUrl = ORIGIN + url.pathname + url.search;
  const upstream = await fetch(upstreamUrl, {{
    method: request.method,
    headers: request.headers,
    body: ["GET", "HEAD"].includes(request.method) ? undefined : request.body,
  }});

  const contentType = upstream.headers.get("Content-Type") || "";

  // 3a) text/html: inject body bait
  if (contentType.includes("text/html")) {{
    const newBody = await injectHtml(upstream);
    return new Response(newBody, withBaitHeaders({{
      status: upstream.status,
      headers: upstream.headers,
    }}));
  }}

  // 3b) other types: just add bait headers, leave body alone
  return new Response(upstream.body, withBaitHeaders({{
    status: upstream.status,
    headers: upstream.headers,
  }}));
}}

export default {{
  async fetch(request, env, ctx) {{
    return handle(request);
  }},
}};

// For service-worker-format Workers (legacy), use this instead:
// addEventListener("fetch", event => event.respondWith(handle(event.request)));
"""
