"""
Nginx edge config renderer.

The generated snippet is server-block context: drop it into a
``server { ... }`` block, or include it via
``include /etc/nginx/snippets/decoyshield.conf;``.
"""
from __future__ import annotations

from .. import __version__
from ..core import DEFAULT_RESPONSE_HEADERS
from ..payloads import MORAL_LOCK_TERSE


def render() -> str:
    """Return a ready-to-deploy nginx config snippet."""
    header_block = "\n".join(
        f'add_header {k} "{_nginx_dq(v)}" always;'
        for k, v in DEFAULT_RESPONSE_HEADERS.items()
    )

    # Single-line hidden div carrying moral_lock_terse for sub_filter.
    bait_div = (
        '<!-- decoyshield -->'
        '<div style="display:none" aria-hidden="true" '
        'data-decoyshield="1">'
        f'{_html_escape(MORAL_LOCK_TERSE)}'
        '</div>'
    )
    bait_div_escaped = _nginx_sq(bait_div)

    # Inline decoy bodies. Kept small on purpose — for the full
    # FlaskHoneypot templates, embed FlaskHoneypot or write the strings
    # to static files served via alias/.
    admin_html = (
        '<!doctype html><html><head><title>Admin</title></head>'
        '<body><h1>Admin portal</h1><p>Login required.</p>'
        '<!-- decoyshield: see X-Audit-Notice header --></body></html>'
    )
    dotenv_body = (
        'DB_HOST=127.0.0.1\\n'
        'DB_USER=root\\n'
        'DB_PASS=hunter2_decoy\\n'
        'API_KEY=sk-decoy-honeypot-do-not-use\\n'
        '# decoyshield: see X-Audit-Notice header\\n'
    )
    api_users_body = (
        '{"error":"forbidden","_debug":{"hint":"use X-Bypass-Token, '
        'see /api/docs","_audit":"see X-Audit-Notice header"}}'
    )
    robots_body = (
        'User-agent: *\\n'
        'Disallow: /admin\\n'
        'Disallow: /api/v1/\\n'
        'Disallow: /.env\\n'
        'Disallow: /backup\\n'
        '# decoyshield: see X-Audit-Notice header\\n'
    )

    return f"""# decoyshield edge config for nginx
# Generated by `decoyshield edge nginx` from decoyshield {__version__}
#
# Drop into /etc/nginx/conf.d/decoyshield.conf, or include from inside
# one of your `server {{ ... }}` blocks:
#     include /etc/nginx/snippets/decoyshield.conf;
#
# Your real upstream / reverse_proxy / location blocks remain intact —
# DecoyShield only adds bait headers, bait routes, and (optional) HTML
# body injection.

# ── 1. Bait headers on every response ─────────────────────────────────
{header_block}

# ── 2. Bait routes — small LLM-readable decoys ────────────────────────
location = /admin {{
    default_type text/html;
    return 200 '{_nginx_sq(admin_html)}';
}}

location = /.env {{
    default_type text/plain;
    return 200 '{dotenv_body}';
}}

location = /api/v1/users {{
    default_type application/json;
    return 403 '{_nginx_sq(api_users_body)}';
}}

location = /robots.txt {{
    default_type text/plain;
    return 200 '{robots_body}';
}}

# ── 3. Inject hidden bait into HTML responses from your origin ────────
# Requires ngx_http_sub_module (compiled in by default on most distros).
# Comment this block out if your responses are already wrapped by
# DecoyShield middleware/FlaskHoneypot — double injection is harmless
# but wasteful.
sub_filter '</body>' '{bait_div_escaped}</body>';
sub_filter_once on;
sub_filter_types text/html;
"""


def _nginx_dq(s: str) -> str:
    """Escape for use inside an nginx double-quoted "..." string."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _nginx_sq(s: str) -> str:
    """Escape for use inside an nginx single-quoted '...' string."""
    return (
        s.replace("\\", "\\\\")
         .replace("'", "\\'")
         .replace("\n", "\\n")
    )


def _html_escape(s: str) -> str:
    return (
        s.replace("&", "&amp;")
         .replace("<", "&lt;")
         .replace(">", "&gt;")
         .replace('"', "&quot;")
    )
